services:
  - type: web
    name: telegram-break-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
