services:
  - type: web
    name: telegram-bot
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_v2.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
