services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_v2.py"
    envVars:
      - key: BOT_TOKEN
        value: false
